.TH "cuvis_event_component_data_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis_event_component_data_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCUVIS_HANDLE\fP \fBcompent_id\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBCUVIS_HANDLE\fP cuvis_event_component_data_t::compent_id"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
