.TH "cuvis::image_t< data_t >" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::image_t< data_t > \- Image data from a measurement\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.PP
Inherits \fBcuvis::common_image_t< data_t >\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t const  * \fB_wavelength\fP"
.br
.RI "wavelength vector\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMeasurement\fP"
.br
.ti -1c
.RI "class \fBViewer\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename data_t>
.br
struct cuvis::image_t< data_t >"Image data from a measurement\&. 

See \fBcommon_image_t\fP for single pixel access\&. The \fB_wavelength\fP is either a nullptr or, if set contains the cube's wavelengths in nano meter\&.
.PP
\fBTemplate Parameters\fP
.RS 4
\fIdata_t\fP The pixel bit depth, either std::uint8_t, std::uint16_t, std::uint32_t or float 
.RE
.PP

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename data_t > friend class \fBMeasurement\fP\fC [friend]\fP"

.SS "template<typename data_t > friend class \fBViewer\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename data_t > uint32_t const* \fBcuvis::image_t\fP< data_t >::_wavelength"

.PP
wavelength vector\&. nullptr, an array of size \fB_channels\fP contianing the wavelengths in nano meter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
