.TH "cuvis_view_data_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis_view_data_t \- The view meta structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCUVIS_CHAR\fP \fBid\fP [\fBCUVIS_MAXBUF\fP]"
.br
.RI "The id of the view\&. "
.ti -1c
.RI "\fBCUVIS_VIEW_CATEGORY\fP \fBcategory\fP"
.br
.RI "the type of view data "
.ti -1c
.RI "\fBCUVIS_IMBUFFER\fP \fBdata\fP"
.br
.RI "the actual data\&. "
.ti -1c
.RI "\fBCUVIS_INT\fP \fBshow\fP"
.br
.RI "1 if dataset is intended for showing, 0 else "
.in -1c
.SH "Detailed Description"
.PP 
The view meta structure\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBCUVIS_VIEW_CATEGORY\fP cuvis_view_data_t::category"

.PP
the type of view data 
.SS "\fBCUVIS_IMBUFFER\fP cuvis_view_data_t::data"

.PP
the actual data\&. View data is always 8 bit, i\&.e\&. imbuffer bytes = 1 
.SS "\fBCUVIS_CHAR\fP cuvis_view_data_t::id[\fBCUVIS_MAXBUF\fP]"

.PP
The id of the view\&. 
.SS "\fBCUVIS_INT\fP cuvis_view_data_t::show"

.PP
1 if dataset is intended for showing, 0 else 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
