.TH "cuvis::SensorInfoData" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::SensorInfoData \- sensor info data structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSensorInfoData\fP (\fBsensor_info_t\fP const &info)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBaverages\fP"
.br
.RI "number of averages used "
.ti -1c
.RI "int32_t \fBtemperature\fP"
.br
.RI "the sensors's temperature while readout (0 if not applicable) "
.ti -1c
.RI "double \fBgain\fP"
.br
.RI "gain value while recording "
.ti -1c
.RI "\fBtimestamp_t\fP \fBreadout_time\fP"
.br
.RI "the timestamp (UTC) of the image readout (senor's hardware clock ) "
.in -1c
.SH "Detailed Description"
.PP 
sensor info data structure 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::SensorInfoData::SensorInfoData (\fBsensor_info_t\fP const & info)"

.SH "Member Data Documentation"
.PP 
.SS "uint32_t cuvis::SensorInfoData::averages"

.PP
number of averages used 
.SS "double cuvis::SensorInfoData::gain"

.PP
gain value while recording 
.SS "\fBtimestamp_t\fP cuvis::SensorInfoData::readout_time"

.PP
the timestamp (UTC) of the image readout (senor's hardware clock ) 
.SS "int32_t cuvis::SensorInfoData::temperature"

.PP
the sensors's temperature while readout (0 if not applicable) 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
