.TH "cuvis::General" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::General
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBset_log_level\fP (\fBint_t\fP lvl)"
.br
.ti -1c
.RI "static void \fBset_exception_locale\fP (std::string const &locale='')"
.br
.ti -1c
.RI "static void \fBregister_log_callback\fP (std::function< void(char const *, \fBloglevel_t\fP)> callback, \fBint_t\fP min_lvl)"
.br
.ti -1c
.RI "static void \fBreset_log_callback\fP ()"
.br
.ti -1c
.RI "static void \fBregister_log_callback_localized\fP (std::function< void(wchar_t const *, \fBloglevel_t\fP)> callback, \fBint_t\fP min_lvl, std::string const &loc_id)"
.br
.ti -1c
.RI "static void \fBreset_log_callback_localized\fP ()"
.br
.ti -1c
.RI "static std::string \fBversion\fP ()"
.br
.ti -1c
.RI "static void \fBinit\fP (std::string const &settings_path)"
.br
.ti -1c
.RI "static \fBint_t\fP \fBregister_event_callback\fP (\fBcpp_event_callback_t\fP callback, \fBint_t\fP i_type)"
.br
.ti -1c
.RI "static void \fBunregister_event_callback\fP (\fBint_t\fP i_handler_id)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void cuvis::General::init (std::string const & settings_path)\fC [static]\fP"

.SS "static \fBint_t\fP cuvis::General::register_event_callback (\fBcpp_event_callback_t\fP callback, \fBint_t\fP i_type)\fC [static]\fP"

.SS "static void cuvis::General::register_log_callback (std::function< void(char const *, \fBloglevel_t\fP)> callback, \fBint_t\fP min_lvl)\fC [static]\fP"

.SS "static void cuvis::General::register_log_callback_localized (std::function< void(wchar_t const *, \fBloglevel_t\fP)> callback, \fBint_t\fP min_lvl, std::string const & loc_id)\fC [static]\fP"

.SS "static void cuvis::General::reset_log_callback ()\fC [static]\fP"

.SS "static void cuvis::General::reset_log_callback_localized ()\fC [static]\fP"

.SS "static void cuvis::General::set_exception_locale (std::string const & locale = \fC''\fP)\fC [static]\fP"

.SS "static void cuvis::General::set_log_level (\fBint_t\fP lvl)\fC [static]\fP"

.SS "static void cuvis::General::unregister_event_callback (\fBint_t\fP i_handler_id)\fC [static]\fP"

.SS "static std::string cuvis::General::version ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
