.TH "cuvis::aux::spectral::spectral_mean_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::aux::spectral::spectral_mean_t \- Couple of wavelength, respective mean value and standard deviation with default values\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis_spectral\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBwavelength\fP"
.br
.RI "The wavelength (in nm)\&. "
.ti -1c
.RI "double \fBvalue\fP"
.br
.RI "The value (counts/reflectance, depending on input)\&. "
.ti -1c
.RI "double \fBstd\fP"
.br
.RI "The standard deviation for the repsective value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Couple of wavelength, respective mean value and standard deviation with default values\&. 

Basic type for spectral information\&. 
.SH "Member Data Documentation"
.PP 
.SS "double cuvis::aux::spectral::spectral_mean_t::std"
\fBInitial value:\fP
.PP
.nf
= 
        0\&.0
.fi
.PP
The standard deviation for the repsective value\&. 
.SS "double cuvis::aux::spectral::spectral_mean_t::value"
\fBInitial value:\fP
.PP
.nf
= 
        -999\&.0
.fi
.PP
The value (counts/reflectance, depending on input)\&. 
.SS "std::uint32_t cuvis::aux::spectral::spectral_mean_t::wavelength"

.PP
The wavelength (in nm)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
