.TH "cuvis::aux::spectral" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::aux::spectral \- Helper functions and structures for spectral calculation\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhistogram_t\fP"
.br
.RI "Couple of wavelength, respective count and occurrence\&. "
.ti -1c
.RI "struct \fBpoint_t\fP"
.br
.RI "2-dimensional definition of a single point "
.ti -1c
.RI "struct \fBspectral_mean_t\fP"
.br
.RI "Couple of wavelength, respective mean value and standard deviation with default values\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBspectrum_t\fP = std::vector< \fBspectral_mean_t\fP >"
.br
.RI "A vector type for describing a spectrum with mean and standard deviation\&. "
.ti -1c
.RI "using \fBhistogram_vector_t\fP = std::vector< \fBhistogram_t\fP >"
.br
.RI "A vector type for describing a histogram for individual wavelengths with counts and ocurrences\&. "
.ti -1c
.RI "using \fBpolygon_t\fP = std::vector< \fBpoint_t\fP >"
.br
.RI "A vector type for describing a polygon with x and y coordinates\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename data_t > \fBspectrum_t\fP \fBget_spectrum_polygon\fP (\fBimage_t\fP< data_t > const &img, \fBpolygon_t\fP const &poly)"
.br
.RI "Calculates a spectrum for a polygon\&. "
.ti -1c
.RI "template<typename data_t > \fBhistogram_vector_t\fP \fBget_histogram\fP (\fBimage_t\fP< data_t > const &img, size_t histogram_min_size, size_t count_bins, size_t wavelength_bins, bool detect_max_value)"
.br
.RI "Calculates a histogram for an image\&. "
.in -1c
.SH "Detailed Description"
.PP 
Helper functions and structures for spectral calculation\&. 

Spectral helpers include structures and methods to extract spectra of type spectrum_t from polygones of type polygon_t and calculate wavelength specific histograms of type histogram_vector_t\&. 
.SH "Typedef Documentation"
.PP 
.SS "using \fBcuvis::aux::spectral::histogram_vector_t\fP = typedef std::vector<\fBhistogram_t\fP>"

.PP
A vector type for describing a histogram for individual wavelengths with counts and ocurrences\&. 
.SS "using \fBcuvis::aux::spectral::polygon_t\fP = typedef std::vector<\fBpoint_t\fP>"

.PP
A vector type for describing a polygon with x and y coordinates\&. 
.SS "using \fBcuvis::aux::spectral::spectrum_t\fP = typedef std::vector<\fBspectral_mean_t\fP>"

.PP
A vector type for describing a spectrum with mean and standard deviation\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename data_t > \fBhistogram_vector_t\fP cuvis::aux::spectral::get_histogram (\fBimage_t\fP< data_t > const & img, size_t histogram_min_size, size_t count_bins, size_t wavelength_bins, bool detect_max_value)"

.PP
Calculates a histogram for an image\&. Calculates a histogram for all wavelengths with counts and occurence for a given Cuvis \fBMeasurement\fP Image\&.
.PP
\fBParameters\fP
.RS 4
\fIimg\fP Cuvis Image data from \fBMeasurement\fP 
.br
\fIhistogram_min_size\fP Lower limit for image data points 
.br
\fIcount_bins\fP Number of count bins of histogram 
.br
\fIwavelength_bins\fP Number of wavelength bins of histogram 
.RE
.PP
\fBReturns\fP
.RS 4
A vector of type \fBhistogram_vector_t\fP 
.RE
.PP

.SS "template<typename data_t > \fBspectrum_t\fP cuvis::aux::spectral::get_spectrum_polygon (\fBimage_t\fP< data_t > const & img, \fBpolygon_t\fP const & poly)"

.PP
Calculates a spectrum for a polygon\&. Calculates a spectrum with mean and standard deviation for all wavelengths for a given polygon, i\&.e\&. vector of points\&.
.PP
\fBParameters\fP
.RS 4
\fIimg\fP Cuvis Image data from \fBMeasurement\fP 
.br
\fIpoly\fP Polygon for subsetting the image (can also be only 1 point) 
.RE
.PP
\fBReturns\fP
.RS 4
A vector of type \fBspectrum_t\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
