.TH "cuvis_reserved_keys" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis_reserved_keys \- Reserved Keys
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCUVIS_MESU_CUBE_KEY\fP   'cube'"
.br
.RI "name of the data field for the hyperspectral cube (in all modes except \fBPreview\fP) "
.ti -1c
.RI "#define \fBCUVIS_MESU_PAN_KEY\fP   'pan'"
.br
.RI "name of the pan image (pixels registered to \fBCUVIS_MESU_CUBE_KEY\fP) "
.ti -1c
.RI "#define \fBCUVIS_MESU_GPS_KEY\fP   'GPS_data'"
.br
.RI "name of the GPS data field, if available "
.ti -1c
.RI "#define \fBCUVIS_MESU_PREVIEW_KEY\fP   'preview'"
.br
.RI "name of the generate preview image, if available\&. "
.ti -1c
.RI "#define \fBCUVIS_MESU_DARKREF_KEY\fP   'dark_ref'"
.br
.RI "If this field is present, a dark was set while recording the measurement\&. "
.ti -1c
.RI "#define \fBCUVIS_MESU_WHITEREF_KEY\fP   'white_ref'"
.br
.RI "If this field is present, a white was set while recording the measurement\&. "
.ti -1c
.RI "#define \fBCUVIS_MESU_WHITEDARKREF_KEY\fP   'white_dark_ref'"
.br
.RI "If this field is present, a white's dark was set while recording the measurement\&. "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_OVERILLUMINATED_KEY\fP   'Flag_DataIsOverilluminated'"
.br
.RI "see \fBCUVIS_MESU_FLAG_OVERILLUMINATED\fP "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_POOR_REFERENCE_KEY\fP   'Flag_DataUsesPoorReference'"
.br
.RI "see \fBCUVIS_MESU_FLAG_POOR_REFERENCE\fP "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_POOR_WHITE_BALANCING_KEY\fP   'Flag_PoorWhiteBalancingData'"
.br
.RI "see \fBCUVIS_MESU_FLAG_POOR_WHITE_BALANCING\fP "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_DARK_INTTIME_KEY\fP   'Flag_IntegrationTimeMismatchDark'"
.br
.RI "see \fBCUVIS_MESU_FLAG_DARK_INTTIME\fP "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_DARK_TEMP_KEY\fP   'Flag_TemperatureMismatchDark'"
.br
.RI "see \fBCUVIS_MESU_FLAG_DARK_TEMP\fP "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_WHITE_INTTIME_KEY\fP     'Flag_IntegrationTimeMismatchWhiteDark'"
.br
.RI "see \fBCUVIS_MESU_FLAG_WHITE_INTTIME\fP "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_WHITE_TEMP_KEY\fP   'Flag_TemperatureMismatchWhiteDark'"
.br
.RI "see \fBCUVIS_MESU_FLAG_WHITE_TEMP\fP "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_WHITEDARK_INTTIME_KEY\fP     'Flag_IntegrationTimeMismatchWhiteDark'"
.br
.RI "see \fBCUVIS_MESU_FLAG_WHITEDARK_INTTIME\fP "
.ti -1c
.RI "#define \fBCUVIS_MESU_FLAG_WHITEDARK_TEMP_KEY\fP   'Flag_TemperatureMismatchWhiteDark'"
.br
.RI "see \fBCUVIS_MESU_FLAG_WHITEDARK_TEMP\fP "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CUVIS_MESU_CUBE_KEY   'cube'"

.PP
name of the data field for the hyperspectral cube (in all modes except \fBPreview\fP) 
.SS "#define CUVIS_MESU_DARKREF_KEY   'dark_ref'"

.PP
If this field is present, a dark was set while recording the measurement\&. This is the dark that is implicitly loaded when a processing context is created with the current measurement and used, if a dark is needed (unless overwritten by \fBcuvis_proc_cont_set_reference\fP ) The reference file should be located in \&.\&./Calibration/<reference-name>\&.cu3 or the precise path defined by the string value of the data tag 
.SS "#define CUVIS_MESU_FLAG_DARK_INTTIME_KEY   'Flag_IntegrationTimeMismatchDark'"

.PP
see \fBCUVIS_MESU_FLAG_DARK_INTTIME\fP 
.SS "#define CUVIS_MESU_FLAG_DARK_TEMP_KEY   'Flag_TemperatureMismatchDark'"

.PP
see \fBCUVIS_MESU_FLAG_DARK_TEMP\fP 
.SS "#define CUVIS_MESU_FLAG_OVERILLUMINATED_KEY   'Flag_DataIsOverilluminated'"

.PP
see \fBCUVIS_MESU_FLAG_OVERILLUMINATED\fP 
.SS "#define CUVIS_MESU_FLAG_POOR_REFERENCE_KEY   'Flag_DataUsesPoorReference'"

.PP
see \fBCUVIS_MESU_FLAG_POOR_REFERENCE\fP 
.SS "#define CUVIS_MESU_FLAG_POOR_WHITE_BALANCING_KEY   'Flag_PoorWhiteBalancingData'"

.PP
see \fBCUVIS_MESU_FLAG_POOR_WHITE_BALANCING\fP 
.SS "#define CUVIS_MESU_FLAG_WHITE_INTTIME_KEY     'Flag_IntegrationTimeMismatchWhiteDark'"

.PP
see \fBCUVIS_MESU_FLAG_WHITE_INTTIME\fP 
.SS "#define CUVIS_MESU_FLAG_WHITE_TEMP_KEY   'Flag_TemperatureMismatchWhiteDark'"

.PP
see \fBCUVIS_MESU_FLAG_WHITE_TEMP\fP 
.SS "#define CUVIS_MESU_FLAG_WHITEDARK_INTTIME_KEY     'Flag_IntegrationTimeMismatchWhiteDark'"

.PP
see \fBCUVIS_MESU_FLAG_WHITEDARK_INTTIME\fP 
.SS "#define CUVIS_MESU_FLAG_WHITEDARK_TEMP_KEY   'Flag_TemperatureMismatchWhiteDark'"

.PP
see \fBCUVIS_MESU_FLAG_WHITEDARK_TEMP\fP 
.SS "#define CUVIS_MESU_GPS_KEY   'GPS_data'"

.PP
name of the GPS data field, if available 
.SS "#define CUVIS_MESU_PAN_KEY   'pan'"

.PP
name of the pan image (pixels registered to \fBCUVIS_MESU_CUBE_KEY\fP) 
.SS "#define CUVIS_MESU_PREVIEW_KEY   'preview'"

.PP
name of the generate preview image, if available\&. The preview will be generated by the \fBcuvis_proc_cont_apply\fP function 
.SS "#define CUVIS_MESU_WHITEDARKREF_KEY   'white_dark_ref'"

.PP
If this field is present, a white's dark was set while recording the measurement\&. This is the white' dark that is implicitly loaded when a processing context is created with the current measurement and used, if a dark is needed (unless overwritten by \fBcuvis_proc_cont_set_reference\fP ) The reference file should be located in \&.\&./Calibration/<reference-name>\&.cu3 or the precise path defined by the string value of the data tag 
.SS "#define CUVIS_MESU_WHITEREF_KEY   'white_ref'"

.PP
If this field is present, a white was set while recording the measurement\&. This is the white that is implicitly loaded when a processing context is created with the current measurement and used, if a dark is needed (unless overwritten by \fBcuvis_proc_cont_set_reference\fP ) The reference file should be located in \&.\&./Calibration/<reference-name>\&.cu3 or the precise path defined by the string value of the data tag 
.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
