.TH "cuvis::aux::spectral::histogram_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::aux::spectral::histogram_t \- Couple of wavelength, respective count and occurrence\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis_spectral\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBwavelength\fP"
.br
.RI "The center wavelength (in nm)\&. "
.ti -1c
.RI "std::vector< std::uint64_t > \fBcount\fP"
.br
.RI "The count for a specific center wavelength\&. "
.ti -1c
.RI "std::vector< std::uint64_t > \fBoccurrence\fP"
.br
.RI "The occurence for the respective count\&. "
.in -1c
.SH "Detailed Description"
.PP 
Couple of wavelength, respective count and occurrence\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::vector<std::uint64_t> cuvis::aux::spectral::histogram_t::count"

.PP
The count for a specific center wavelength\&. 
.SS "std::vector<std::uint64_t> cuvis::aux::spectral::histogram_t::occurrence"

.PP
The occurence for the respective count\&. 
.SS "std::uint32_t cuvis::aux::spectral::histogram_t::wavelength"

.PP
The center wavelength (in nm)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
