.TH "cuvis::SessionFile" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::SessionFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSessionFile\fP (std::filesystem::path const &path)"
.br
.ti -1c
.RI "std::optional< \fBMeasurement\fP > \fBget_mesu\fP (\fBint_t\fP frameNo, \fBcuvis_session_item_type_t\fP type=\fBcuvis_session_item_type_t::session_item_type_frames\fP) const"
.br
.ti -1c
.RI "std::optional< \fBMeasurement\fP > \fBget_ref\fP (\fBint_t\fP refNo, \fBcuvis_reference_type_t\fP type) const"
.br
.ti -1c
.RI "\fBint_t\fP \fBget_size\fP (\fBcuvis_session_item_type_t\fP type=\fBcuvis_session_item_type_t::session_item_type_frames\fP) const"
.br
.RI "get size of the \fBSessionFile\fP "
.ti -1c
.RI "double \fBget_fps\fP () const"
.br
.RI "get the frame rate of this session "
.ti -1c
.RI "\fBCUVIS_OPERATION_MODE\fP \fBget_operation_mode\fP () const"
.br
.RI "get operation mode of the session "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCalibration\fP"
.br
.ti -1c
.RI "class \fBProcessingContext\fP"
.br
.ti -1c
.RI "class \fBAcquisitionContext\fP"
.br
.ti -1c
.RI "class \fBWorker\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::SessionFile::SessionFile (std::filesystem::path const & path)"

.SH "Member Function Documentation"
.PP 
.SS "double cuvis::SessionFile::get_fps () const"

.PP
get the frame rate of this session 
.SS "std::optional< \fBMeasurement\fP > cuvis::SessionFile::get_mesu (\fBint_t\fP frameNo, \fBcuvis_session_item_type_t\fP type = \fC\fBcuvis_session_item_type_t::session_item_type_frames\fP\fP) const"

.SS "\fBCUVIS_OPERATION_MODE\fP cuvis::SessionFile::get_operation_mode () const"

.PP
get operation mode of the session 
.SS "std::optional< \fBMeasurement\fP > cuvis::SessionFile::get_ref (\fBint_t\fP refNo, \fBcuvis_reference_type_t\fP type) const"

.SS "\fBint_t\fP cuvis::SessionFile::get_size (\fBcuvis_session_item_type_t\fP type = \fC\fBcuvis_session_item_type_t::session_item_type_frames\fP\fP) const"

.PP
get size of the \fBSessionFile\fP 
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBAcquisitionContext\fP\fC [friend]\fP"

.SS "friend class \fBCalibration\fP\fC [friend]\fP"

.SS "friend class \fBProcessingContext\fP\fC [friend]\fP"

.SS "friend class \fBWorker\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
