.TH "cuvis_export_view_settings_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis_export_view_settings_t \- Additional settings for exporting to a userplugin view\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCUVIS_CHAR\fP const  * \fBuserplugin\fP"
.br
.RI "The userplugin xml string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Additional settings for exporting to a userplugin view\&. 

See also \fBcuvis_export_general_settings_t\fP 
.SH "Member Data Documentation"
.PP 
.SS "\fBCUVIS_CHAR\fP const* cuvis_export_view_settings_t::userplugin"

.PP
The userplugin xml string\&. See userplugin manual\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
