.TH "cuvis::ViewExporter" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::ViewExporter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.PP
Inherits \fBcuvis::Exporter\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBformat_settings_t\fP = \fBcuvis_export_view_settings_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewExporter\fP (\fBViewArgs\fP const &args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBcuvis::ViewExporter::format_settings_t\fP =  \fBcuvis_export_view_settings_t\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::ViewExporter::ViewExporter (\fBViewArgs\fP const & args)"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
