.TH "cuvis::AcquisitionContext::component_state_info_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::AcquisitionContext::component_state_info_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBdisplay_name\fP"
.br
.ti -1c
.RI "bool \fBis_online\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string cuvis::AcquisitionContext::component_state_info_t::display_name"

.SS "bool cuvis::AcquisitionContext::component_state_info_t::is_online"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
