.TH "cuvis::aux::spectral::point_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::aux::spectral::point_t \- 2-dimensional definition of a single point  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis_spectral\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fB_x\fP"
.br
.RI "The x coordinate\&. "
.ti -1c
.RI "double \fB_y\fP"
.br
.RI "The y coordinate\&. "
.in -1c
.SH "Detailed Description"
.PP 
2-dimensional definition of a single point 
.SH "Member Data Documentation"
.PP 
.SS "double cuvis::aux::spectral::point_t::_x"

.PP
The x coordinate\&. (E-W) 
.SS "double cuvis::aux::spectral::point_t::_y"

.PP
The y coordinate\&. (S-N) 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
