.TH "cuvis_export_tiff_settings_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis_export_tiff_settings_t \- Additional settings for exporting tiff\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCUVIS_TIFF_COMPRESSION_MODE\fP \fBcompression_mode\fP"
.br
.RI "the compression mode for tiff export "
.ti -1c
.RI "\fBCUVIS_TIFF_FORMAT\fP \fBformat\fP"
.br
.RI "the tiff export mode / format "
.in -1c
.SH "Detailed Description"
.PP 
Additional settings for exporting tiff\&. 

See also \fBcuvis_export_general_settings_t\fP 
.SH "Member Data Documentation"
.PP 
.SS "\fBCUVIS_TIFF_COMPRESSION_MODE\fP cuvis_export_tiff_settings_t::compression_mode"

.PP
the compression mode for tiff export 
.SS "\fBCUVIS_TIFF_FORMAT\fP cuvis_export_tiff_settings_t::format"

.PP
the tiff export mode / format 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
