.TH "cuvis::EnviExporter" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::EnviExporter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.PP
Inherits \fBcuvis::Exporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnviExporter\fP (\fBEnviArgs\fP const &args)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::EnviExporter::EnviExporter (\fBEnviArgs\fP const & args)"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
