.TH "cuvis_mesu_metadata_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis_mesu_metadata_t \- The measurement meta structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCUVIS_CHAR\fP \fBname\fP [\fBCUVIS_MAXBUF\fP]"
.br
.RI "The name of the measurement\&. "
.ti -1c
.RI "\fBCUVIS_CHAR\fP \fBpath\fP [\fBCUVIS_MAXBUF\fP]"
.br
.RI "The output file path\&. "
.ti -1c
.RI "\fBCUVIS_CHAR\fP \fBcomment\fP [\fBCUVIS_MAXBUF\fP]"
.br
.RI "The User Comment linked to the measurement\&. "
.ti -1c
.RI "\fBCUVIS_TIMESTAMP\fP \fBcapture_time\fP"
.br
.RI "The Capture Time of the Measurement\&. "
.ti -1c
.RI "\fBCUVIS_TIMESTAMP\fP \fBfactory_calibration\fP"
.br
.RI "The factory calibration date of the device\&. "
.ti -1c
.RI "\fBCUVIS_CHAR\fP \fBproduct_name\fP [\fBCUVIS_MAXBUF\fP]"
.br
.RI "The name of the device, which took the measurement\&. "
.ti -1c
.RI "\fBCUVIS_CHAR\fP \fBserial_number\fP [\fBCUVIS_MAXBUF\fP]"
.br
.RI "The serial number of the device, which took the measurement\&. "
.ti -1c
.RI "\fBCUVIS_CHAR\fP \fBassembly\fP [\fBCUVIS_MAXBUF\fP]"
.br
.RI "The Assembly Data of the device\&. "
.ti -1c
.RI "double \fBintegration_time\fP"
.br
.RI "The integration time of the measurement (exposure time) in ms\&. "
.ti -1c
.RI "\fBCUVIS_INT\fP \fBaverages\fP"
.br
.RI "Number of averaging taken\&. "
.ti -1c
.RI "double \fBdistance\fP"
.br
.RI "Distance, the measurement was recorded in mm\&. "
.ti -1c
.RI "\fBCUVIS_CHAR\fP \fBsession_info_name\fP [\fBCUVIS_MAXBUF\fP]"
.br
.RI "session_info name "
.ti -1c
.RI "\fBCUVIS_INT\fP \fBsession_info_session_no\fP"
.br
.RI "SessionFile number\&. "
.ti -1c
.RI "\fBCUVIS_INT\fP \fBsession_info_sequence_no\fP"
.br
.RI "Sequence number\&. "
.ti -1c
.RI "\fBCUVIS_PROCESSING_MODE\fP \fBprocessing_mode\fP"
.br
.RI "The actual Capture Mode of the cube\&. "
.ti -1c
.RI "\fBCUVIS_FLAGS\fP \fBmeasurement_flags\fP"
.br
.RI "measurement flags "
.in -1c
.SH "Detailed Description"
.PP 
The measurement meta structure\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBCUVIS_CHAR\fP cuvis_mesu_metadata_t::assembly[\fBCUVIS_MAXBUF\fP]"

.PP
The Assembly Data of the device\&. 
.SS "\fBCUVIS_INT\fP cuvis_mesu_metadata_t::averages"

.PP
Number of averaging taken\&. 
.SS "\fBCUVIS_TIMESTAMP\fP cuvis_mesu_metadata_t::capture_time"

.PP
The Capture Time of the Measurement\&. 
.SS "\fBCUVIS_CHAR\fP cuvis_mesu_metadata_t::comment[\fBCUVIS_MAXBUF\fP]"

.PP
The User Comment linked to the measurement\&. 
.SS "double cuvis_mesu_metadata_t::distance"

.PP
Distance, the measurement was recorded in mm\&. If not provided, value is -1 
.SS "\fBCUVIS_TIMESTAMP\fP cuvis_mesu_metadata_t::factory_calibration"

.PP
The factory calibration date of the device\&. 
.SS "double cuvis_mesu_metadata_t::integration_time"

.PP
The integration time of the measurement (exposure time) in ms\&. 
.SS "\fBCUVIS_FLAGS\fP cuvis_mesu_metadata_t::measurement_flags"

.PP
measurement flags 
.SS "\fBCUVIS_CHAR\fP cuvis_mesu_metadata_t::name[\fBCUVIS_MAXBUF\fP]"

.PP
The name of the measurement\&. 
.SS "\fBCUVIS_CHAR\fP cuvis_mesu_metadata_t::path[\fBCUVIS_MAXBUF\fP]"

.PP
The output file path\&. 
.SS "\fBCUVIS_PROCESSING_MODE\fP cuvis_mesu_metadata_t::processing_mode"

.PP
The actual Capture Mode of the cube\&. 
.SS "\fBCUVIS_CHAR\fP cuvis_mesu_metadata_t::product_name[\fBCUVIS_MAXBUF\fP]"

.PP
The name of the device, which took the measurement\&. 
.SS "\fBCUVIS_CHAR\fP cuvis_mesu_metadata_t::serial_number[\fBCUVIS_MAXBUF\fP]"

.PP
The serial number of the device, which took the measurement\&. 
.SS "\fBCUVIS_CHAR\fP cuvis_mesu_metadata_t::session_info_name[\fBCUVIS_MAXBUF\fP]"

.PP
session_info name 
.SS "\fBCUVIS_INT\fP cuvis_mesu_metadata_t::session_info_sequence_no"

.PP
Sequence number\&. Increases with each recorded frame\&. Reset, if session_no changes 
.SS "\fBCUVIS_INT\fP cuvis_mesu_metadata_t::session_info_session_no"

.PP
SessionFile number\&. Will be increased by stopping & starting recording 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
