.TH "cuvis_gps_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis_gps_t \- The gps data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBlongitude\fP"
.br
.RI "gps longitude in decimal degrees "
.ti -1c
.RI "double \fBlatitude\fP"
.br
.RI "gps latitude in decimal degrees "
.ti -1c
.RI "double \fBaltitude\fP"
.br
.RI "gps altitude in meters "
.ti -1c
.RI "\fBCUVIS_TIMESTAMP\fP \fBtime\fP"
.br
.RI "the timestamp (UTC) while recoding the gps\&. "
.in -1c
.SH "Detailed Description"
.PP 
The gps data structure\&. 
.SH "Member Data Documentation"
.PP 
.SS "double cuvis_gps_t::altitude"

.PP
gps altitude in meters 
.SS "double cuvis_gps_t::latitude"

.PP
gps latitude in decimal degrees 
.SS "double cuvis_gps_t::longitude"

.PP
gps longitude in decimal degrees 
.SS "\fBCUVIS_TIMESTAMP\fP cuvis_gps_t::time"

.PP
the timestamp (UTC) while recoding the gps\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
