.TH "cuvis::WorkerArgs" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::WorkerArgs \- settings for the worker  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorkerArgs\fP ()"
.br
.RI "Constructor to create default parameters\&. "
.ti -1c
.RI "\fBoperator cuvis_worker_settings_t\fP () const"
.br
.RI "convert to C - SDK settings structure "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBworker_count\fP"
.br
.RI "Number of threads\&. "
.ti -1c
.RI "std::chrono::milliseconds \fBpoll_interval\fP"
.br
.RI "internal poll interval in milliseconds\&. "
.ti -1c
.RI "bool \fBkeep_out_of_sequence\fP"
.br
.RI "If images are retrieved out of sequence, do not drop them (if set to 1)\&. "
.ti -1c
.RI "int \fBworker_queue_size\fP"
.br
.ti -1c
.RI "int \fBworker_queue_hard_limit\fP"
.br
.ti -1c
.RI "int \fBworker_queue_soft_limit\fP"
.br
.ti -1c
.RI "bool \fBcan_drop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
settings for the worker 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::WorkerArgs::WorkerArgs ()"

.PP
Constructor to create default parameters\&. 
.SH "Member Function Documentation"
.PP 
.SS "cuvis::WorkerArgs::operator \fBcuvis_worker_settings_t\fP () const"

.PP
convert to C - SDK settings structure settings for the worker
.SH "Member Data Documentation"
.PP 
.SS "bool cuvis::WorkerArgs::can_drop"

.SS "bool cuvis::WorkerArgs::keep_out_of_sequence"

.PP
If images are retrieved out of sequence, do not drop them (if set to 1)\&. 
.PP
\fBNote\fP
.RS 4
Typically, out-of sequence images occur, when the system can't keep up\&. You should reduce FPS or reduce disable processing\&. 
.RE
.PP

.SS "std::chrono::milliseconds cuvis::WorkerArgs::poll_interval"

.PP
internal poll interval in milliseconds\&. If set to 0, the internal default (10ms) is used 
.SS "unsigned cuvis::WorkerArgs::worker_count"

.PP
Number of threads\&. Number of threads\&. give the number of worker threads to be used\&. If set to 0, the system's hardware concurrency is used (e\&.g 12 for a 6core/12 threads - CPU) 
.SS "int cuvis::WorkerArgs::worker_queue_hard_limit"

.SS "int cuvis::WorkerArgs::worker_queue_size"

.SS "int cuvis::WorkerArgs::worker_queue_soft_limit"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
