.TH "cuvis::ViewArgs" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::ViewArgs \- viewer settings  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.PP
Inherits \fBcuvis::GeneralExportArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewArgs\fP ()"
.br
.RI "Constructor to create default parameters\&. "
.ti -1c
.RI "\fBoperator cuvis_viewer_settings_t\fP () const"
.br
.RI "convert to C - SDK settings structure "
.ti -1c
.RI "\fBoperator cuvis_export_view_settings_t\fP () const"
.br
.RI "convert to C - SDK settings structure "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBuserplugin\fP"
.br
.RI "The userplugin xml string\&. "
.ti -1c
.RI "bool \fBcomplete\fP"
.br
.RI "also include parts that were not marked as 'show' "
.in -1c
.SH "Detailed Description"
.PP 
viewer settings 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::ViewArgs::ViewArgs ()"

.PP
Constructor to create default parameters\&. 
.SH "Member Function Documentation"
.PP 
.SS "cuvis::ViewArgs::operator \fBcuvis_export_view_settings_t\fP () const"

.PP
convert to C - SDK settings structure Additional settings for exporting to a userplugin view\&. See also \fBcuvis_export_general_settings_t\fP 
.SS "cuvis::ViewArgs::operator \fBcuvis_viewer_settings_t\fP () const"

.PP
convert to C - SDK settings structure viewer settings
.SH "Member Data Documentation"
.PP 
.SS "bool cuvis::ViewArgs::complete"

.PP
also include parts that were not marked as 'show' 
.SS "std::string cuvis::ViewArgs::userplugin"

.PP
The userplugin xml string\&. See userplugin manual\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
