.TH "cuvis_hooks.hpp" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis_hooks.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <cuvis\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcuvis::aux::Hooks\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcuvis\fP"
.br
.ti -1c
.RI "namespace \fBcuvis::aux\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
