.TH "cuvis::Calibration" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::Calibration \- central calibration Class  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalibration\fP (std::filesystem::path const &path)"
.br
.RI "Create a calibration from factory path\&. "
.ti -1c
.RI "\fBCalibration\fP (\fBSessionFile\fP const &session)"
.br
.RI "Create a calibration from session file\&. "
.ti -1c
.RI "std::vector< \fBcapabilities_t\fP > \fBget_capabilities\fP (\fBCUVIS_OPERATION_MODE\fP mode) const"
.br
.RI "get calibration capabilities "
.ti -1c
.RI "std::string \fBget_id\fP () const"
.br
.RI "get the calibration id "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBProcessingContext\fP"
.br
.ti -1c
.RI "class \fBAcquisitionContext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
central calibration Class 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::Calibration::Calibration (std::filesystem::path const & path)"

.PP
Create a calibration from factory path\&. The calibration is created from a factory path, containing the license and calibration file 'init\&.daq' as well as further calibration files (e\&.g\&. SpRad\&.cu3)\&.
.PP
The calibration is lazy-loading, i\&.e\&. the \fBAcquisitionContext\fP and the \fBProcessingContext\fP will only be initialized, when explicitly called\&.
.PP
\fBNote\fP
.RS 4
do not load multiple calibration instances of the same camera
.RE
.PP
\fBParameters\fP
.RS 4
\fIpath\fP The path to the factory directory 
.RE
.PP

.SS "cuvis::Calibration::Calibration (\fBSessionFile\fP const & session)"

.PP
Create a calibration from session file\&. Create a calibration from an existion session file\&.
.PP
The calibration is lazy-loading, i\&.e\&. the \fBAcquisitionContext\fP and the \fBProcessingContext\fP will only be initialized, when explicitly called\&.
.PP
When you create a processing context from the calibration cerated with this function, you won't have the references from the session file set\&. Use \fBcuvis_proc_cont_create_from_session_file\fP to load a processing context where the referenecs are taken from the session file\&.
.PP
\fBNote\fP
.RS 4
do not load multiple calibration instances of the same camera
.RE
.PP
\fBParameters\fP
.RS 4
\fIsession\fP The session file 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::vector< \fBcapabilities_t\fP > cuvis::Calibration::get_capabilities (\fBCUVIS_OPERATION_MODE\fP mode) const"

.PP
get calibration capabilities 
.PP
\fBParameters\fP
.RS 4
\fImode\fP Operation mode of the camera see also \fBcuvis_operation_mode_t\fP 
.RE
.PP

.SS "std::string cuvis::Calibration::get_id () const"

.PP
get the calibration id 
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBAcquisitionContext\fP\fC [friend]\fP"

.SS "friend class \fBProcessingContext\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
