.TH "cuvis::ProcessingArgs" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::ProcessingArgs \- processing arguments  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessingArgs\fP ()"
.br
.RI "Constructor to create default parameters\&. "
.ti -1c
.RI "\fBoperator cuvis_proc_args_t\fP () const"
.br
.RI "convert to C - SDK settings structure "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprocessing_mode_t\fP \fBprocessing_mode\fP"
.br
.RI "the processing mode to be used\&. "
.ti -1c
.RI "bool \fBallow_recalib\fP"
.br
.RI "allow to use different calibration (expert option) "
.in -1c
.SH "Detailed Description"
.PP 
processing arguments 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::ProcessingArgs::ProcessingArgs ()"

.PP
Constructor to create default parameters\&. 
.SH "Member Function Documentation"
.PP 
.SS "cuvis::ProcessingArgs::operator \fBcuvis_proc_args_t\fP () const"

.PP
convert to C - SDK settings structure processing arguments
.SH "Member Data Documentation"
.PP 
.SS "bool cuvis::ProcessingArgs::allow_recalib"

.PP
allow to use different calibration (expert option) This options allows to process raw data with a different calibration\&. this is, however, limited to the same hardware\&.
.PP
If the hardware was mechanically changed, results may be poor or not usable at all\&. Unless the accuracy of the result can be verified, this option is not recommended\&. 
.SS "\fBprocessing_mode_t\fP cuvis::ProcessingArgs::processing_mode"

.PP
the processing mode to be used\&. use \fBcuvis_proc_cont_is_capable\fP to check, if the mode is currently possible of a specific measurement 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
