.TH "cuvis::Worker::worker_return_t" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::Worker::worker_return_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::optional< \fBMeasurement\fP > \fBmesu\fP"
.br
.ti -1c
.RI "std::optional< \fBViewer::view_data_t\fP > \fBview\fP"
.br
.ti -1c
.RI "std::exception_ptr \fBexception\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::exception_ptr cuvis::Worker::worker_return_t::exception"

.SS "std::optional<\fBMeasurement\fP> cuvis::Worker::worker_return_t::mesu"

.SS "std::optional<\fBViewer::view_data_t\fP> cuvis::Worker::worker_return_t::view"


.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
