.TH "cuvis::EnviArgs" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cuvis::EnviArgs
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cuvis\&.hpp>\fP
.PP
Inherits \fBcuvis::GeneralExportArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnviArgs\fP ()=default"
.br
.RI "Constructor to create default parameters\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "cuvis::EnviArgs::EnviArgs ()\fC [default]\fP"

.PP
Constructor to create default parameters\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
