.TH "examples" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
examples \- Examples
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "Overview"
With the SDK several examples are installed\&. Under Windows you can find the examples in your installation directory (Default: 'C:\\Program Files\\Cuvis\\sdk\\cuvis_c\\examples' or 'C:\\Program Files\\Cuvis\\sdk\\cuvis_cpp\\examples'), under Linux they can be found in '/lib/cuvis/cuvis_c/examples' or '/lib/cuvis/cuvis_cpp/examples' \&. 
.br
 Each Example comes with the precompiled binary, a short \&.sh-script to run the application and the source code file\&. The \&.sh-script requires the bash console\&. Under windows we recommend to use Git Bash\&. 
.br
 Examples 01-04 require the 'sample_data' folder to be present in the installation directory ( Windows: 'C:\\Program Files\\Cuvis\\sdk\\sample_data' , Linux: '/lib/cuvis/sample_data')\&. 
.br
 Examples 05-06 require a camera to be installed and connected\&. 
.br
 
.SS "Compiling examples"
Instead of using the precompiled examples, you can use the provided source code to compile it yourself\&. Under Linux this is quite simple\&. 
.br
.IP "\(bu" 2
for cuvis_c examples:
.IP "  1." 6
sudo apt install gcc
.IP "  2." 6
sudo gcc -o 0X_example main\&.c -L/lib/cuvis -lcuvis
.PP

.IP "\(bu" 2
for cuvis_cpp examples:
.IP "  1." 6
sudo apt install g++
.IP "  2." 6
sudo g++ -o 0X_example main\&.cpp -L/lib/cuvis -lcuvis -std=c++17
.PP

.PP
.SS "01_loadMeasurement"
Load measurement from disk and print the value (count) for all available channels (wavelength) for one specific pixel\&. 
.SS "02_reprocessMeasurement"
Load measurement as well as references (dark, white, distance) from disk and reprocess the measurement to e\&.g\&. reflectance\&. 
.SS "03_exportMeasurement"
Load measurement from disk and save to different file formats\&. 
.SS "04_changeDistance"
Load measurement from disk and reprocess to a new distance\&. 
.SS "05_recordSingleImages"
Setup camera and record measurements via software trigger, aka 'single shot mode' or 'software mode'\&. 
.SS "06_recordVideo"
Setup camera and record measurements via internal clock triggering, aka 'video mode'\&. In this example the worker is used to make use of multithreading (\fBcuvis_worker_create\fP)\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
