.TH "typedefs" 3 "Thu Jun 22 2023" "Version 3.2.0" "CUVIS C++ SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typedefs \- CPP Type definitions from cuvis C sdk\&.
.PP
 \- Theese type definitions are taken from the CUVIS C SDK (see \fBcuvis\&.h\fP)\&.  

.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcuvis::int_t\fP = \fBCUVIS_INT\fP"
.br
.ti -1c
.RI "using \fBcuvis::event_t\fP = \fBCUVIS_EVENT\fP"
.br
.ti -1c
.RI "using \fBcuvis::loglevel_t\fP = \fBcuvis_loglevel_t\fP"
.br
.RI "The available log levels\&. "
.ti -1c
.RI "using \fBcuvis::operation_mode_t\fP = \fBcuvis_operation_mode_t\fP"
.br
.RI "Operation mode of a camera\&. "
.ti -1c
.RI "using \fBcuvis::reference_type_t\fP = \fBcuvis_reference_type_t\fP"
.br
.RI "The type of a reference\&. "
.ti -1c
.RI "using \fBcuvis::processing_mode_t\fP = \fBcuvis_processing_mode_t\fP"
.br
.RI "The processing mode (a\&.k\&.a\&. "
.ti -1c
.RI "using \fBcuvis::pan_sharpening_interpolation_type_t\fP = \fBcuvis_pan_sharpening_interpolation_type_t\fP"
.br
.RI "the pan sharpening interpolation type for scaling up the cube before applying the pan image's weights "
.ti -1c
.RI "using \fBcuvis::pan_sharpening_algorithm_t\fP = \fBcuvis_pan_sharpening_algorithm_t\fP"
.br
.RI "the pan-sharpening algorithm for calculating the pan image's weights "
.ti -1c
.RI "using \fBcuvis::tiff_compression_mode_t\fP = \fBcuvis_tiff_compression_mode_t\fP"
.br
.RI "the tiff compression options "
.ti -1c
.RI "using \fBcuvis::tiff_format_t\fP = \fBcuvis_tiff_format_t\fP"
.br
.RI "the tiff export format\&. "
.ti -1c
.RI "using \fBcuvis::session_info_t\fP = \fBcuvis_session_info_t\fP"
.br
.RI "internal session_info info of acquisition context "
.ti -1c
.RI "using \fBcuvis::mesu_metadata_t\fP = \fBcuvis_mesu_metadata_t\fP"
.br
.RI "The measurement meta structure\&. "
.ti -1c
.RI "using \fBcuvis::sensor_info_t\fP = \fBcuvis_sensor_info_t\fP"
.br
.ti -1c
.RI "using \fBcuvis::hardware_state_t\fP = \fBcuvis_hardware_state_t\fP"
.br
.RI "the state of the hardware "
.ti -1c
.RI "using \fBcuvis::capabilities_t\fP = \fBcuvis_capabilities_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Theese type definitions are taken from the CUVIS C SDK (see \fBcuvis\&.h\fP)\&. 

Please refer to the C types for documentation\&. 
.SH "Typedef Documentation"
.PP 
.SS "using \fBcuvis::capabilities_t\fP = typedef \fBcuvis_capabilities_t\fP"

.PP

.SS "using \fBcuvis::event_t\fP = typedef \fBCUVIS_EVENT\fP"

.PP

.SS "using \fBcuvis::hardware_state_t\fP = typedef \fBcuvis_hardware_state_t\fP"

.PP
the state of the hardware 
.SS "using \fBcuvis::int_t\fP = typedef \fBCUVIS_INT\fP"

.PP

.SS "using \fBcuvis::loglevel_t\fP = typedef \fBcuvis_loglevel_t\fP"

.PP
The available log levels\&. 
.SS "using \fBcuvis::mesu_metadata_t\fP = typedef \fBcuvis_mesu_metadata_t\fP"

.PP
The measurement meta structure\&. 
.SS "using \fBcuvis::operation_mode_t\fP = typedef \fBcuvis_operation_mode_t\fP"

.PP
Operation mode of a camera\&. 
.SS "using \fBcuvis::pan_sharpening_algorithm_t\fP = typedef \fBcuvis_pan_sharpening_algorithm_t\fP"

.PP
the pan-sharpening algorithm for calculating the pan image's weights 
.SS "using \fBcuvis::pan_sharpening_interpolation_type_t\fP = typedef \fBcuvis_pan_sharpening_interpolation_type_t\fP"

.PP
the pan sharpening interpolation type for scaling up the cube before applying the pan image's weights 
.SS "using \fBcuvis::processing_mode_t\fP = typedef \fBcuvis_processing_mode_t\fP"

.PP
The processing mode (a\&.k\&.a\&. capture mode) of a measurement\&. 
.SS "using \fBcuvis::reference_type_t\fP = typedef \fBcuvis_reference_type_t\fP"

.PP
The type of a reference\&. 
.SS "using \fBcuvis::sensor_info_t\fP = typedef \fBcuvis_sensor_info_t\fP"

.PP

.SS "using \fBcuvis::session_info_t\fP = typedef \fBcuvis_session_info_t\fP"

.PP
internal session_info info of acquisition context 
.SS "using \fBcuvis::tiff_compression_mode_t\fP = typedef \fBcuvis_tiff_compression_mode_t\fP"

.PP
the tiff compression options 
.SS "using \fBcuvis::tiff_format_t\fP = typedef \fBcuvis_tiff_format_t\fP"

.PP
the tiff export format\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for CUVIS C++ SDK from the source code\&.
